export const series = [
  {
    id: "yf81-317h-jf",
    name: "Stranger things",
    seriesCount: 5,
    genre: "drama",
    viewes: 6451,
    releaseDate: 2022,
    episodes: [
      { name: "Stranger things serie 1", count: 1 },
      { name: "Stranger things serie 2", count: 2 },
      { name: "Stranger things serie 3", count: 3 },
      { name: "Stranger things serie 4", count: 4 },
      { name: "Stranger things serie 5", count: 5 },
    ],
  },
  {
    id: "a12-fd7h-jg",
    name: "Sherlock Holmes",
    seriesCount: 7,
    genre: "detective",
    viewes: 1820,
    releaseDate: 2019,
    episodes: [
      { name: "Sherlock Holmes serie 1", count: 1 },
      { name: "Sherlock Holmes serie 2", count: 2 },
      { name: "Sherlock Holmes serie 3", count: 3 },
      { name: "Sherlock Holmes serie 4", count: 4 },
      { name: "Sherlock Holmes serie 5", count: 5 },
      { name: "Sherlock Holmes serie 6", count: 6 },
      { name: "Sherlock Holmes serie 7", count: 7 },
    ],
  },
  {
    id: "b34-fgah-1g",
    name: "Lucifer",
    seriesCount: 6,
    genre: "drama",
    viewes: 6754,
    releaseDate: 2021,
    episodes: [
      { name: "Lucifer serie 1", count: 1 },
      { name: "Lucifer serie 2", count: 2 },
      { name: "Lucifer serie 3", count: 3 },
      { name: "Lucifer serie 4", count: 4 },
      { name: "Lucifer serie 5", count: 5 },
      { name: "Lucifer serie 6", count: 6 },
    ],
  },
  {
    id: "c11-mnzh-12",
    name: "Ann with e",
    seriesCount: 3,
    genre: "drama",
    viewes: 9812,
    releaseDate: 2019,
    episodes: [
      { name: "Ann with e serie 1", count: 1 },
      { name: "Ann with e serie 2", count: 2 },
      { name: "Ann with e serie 3", count: 3 },
    ],
  },
  {
    id: "b00-zazh-00",
    name: "The 100",
    seriesCount: 5,
    genre: "fantasy",
    viewes: 7654,
    releaseDate: 2014,
    episodes: [
      { name: "The 100 serie 1", count: 1 },
      { name: "The 100 serie 2", count: 2 },
      { name: "The 100 serie 3", count: 3 },
      { name: "The 100 serie 4", count: 4 },
      { name: "The 100 serie 5", count: 5 },
    ],
  },
  {
    id: "mn1-aaah-12",
    name: "Paper house",
    seriesCount: 5,
    genre: "fantasy",
    viewes: 9165,
    releaseDate: 2019,
    episodes: [
      { name: "Paper house serie 1", count: 1 },
      { name: "Paper house serie 2", count: 2 },
      { name: "Paper house serie 3", count: 3 },
      { name: "Paper house serie 4", count: 4 },
      { name: "Paper house serie 5", count: 5 },
    ],
  },
  {
    id: "mn1-oooo-11",
    name: "Dynasty",
    seriesCount: 7,
    genre: "historical",
    viewes: 1233,
    releaseDate: 2019,
    episodes: [
      { name: "Dynasty serie 1", count: 1 },
      { name: "Dynasty serie 2", count: 2 },
      { name: "Dynasty serie 3", count: 3 },
      { name: "Dynasty serie 4", count: 4 },
      { name: "Dynasty serie 5", count: 5 },
      { name: "Dynasty serie 6", count: 6 },
      { name: "Dynasty serie 7", count: 7 },
    ],
  },
  {
    id: "mn3-jjoo-99",
    name: "Riverdale",
    seriesCount: 7,
    genre: "drama",
    viewes: 6666,
    releaseDate: 2022,
    episodes: [
      { name: "Riverdale serie 1", count: 1 },
      { name: "Riverdale serie 2", count: 2 },
      { name: "Riverdale serie 3", count: 3 },
      { name: "Riverdale serie 4", count: 4 },
      { name: "Riverdale serie 5", count: 5 },
      { name: "Riverdale serie 6", count: 6 },
      { name: "Riverdale serie 7", count: 7 },
    ],
  },
];
